server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: root
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
  output:
    ansi:
      enabled: always
logging:
  level:
    '[com.application.miniproject]': DEBUG
    '[org.hibernate.type]': TRACE
jwt:
  key: ${JWT_SECRET_KEY:localSecret}
default:
  path: /src/assets/profile/0.png
